### ISSUE TITLE
El generador genera demasiados objetos que no son visibles en la cámara

### ISSUE THREAD

**Issue by moeru1** [moeru1/armando-el-rollo#1]
spawn_tiles está siendo llamado con posiciones que van incrementando de manera no acotada, cuando el personaje siempre está en la posición [0, 15] en x. 

https://github.com/moeru1/armando-el-rollo/blob/c0300f767c486e391c6bf59df4201f63cefaccb8/Scenes/Generators/Generator.gd#L20-L36

Además, suponiendo que el juego se está ejecutando a 60 fps, calculando el valor esperado de cuando se cumple la condición en la línea 27 
https://github.com/moeru1/armando-el-rollo/blob/c0300f767c486e391c6bf59df4201f63cefaccb8/Scenes/Generators/Generator.gd#L27

Podemos observar que en promedio se cumple cada 5 llamadas a spawn_tiles (cada 5 fotogramas), eso hace que cada segundo creemos 20 objetos en promedio, que no son visibles. 

Además, en mi opinion pienso que las llamadas a spawn_tiles no deberia estar en función de la cantidad de fotogramas, porque diferentes dispositivos móviles pueden ejecutar el juego a diferente framerate, por ejemplo 30fps, 60 fps, 90 fps, etc. y eso haria que se sea diferente la jugabilidad dependiendo del dispositivo.

Propongo

- Definir de mejor manera cuantos enemigos queremos como máximo en la pantalla y sus respectivas probabilidades
- Simplificar el método spawn_tiles de manera acorde

**Comment by Riczap** [comment]
Me parece buena idea, igual estaba pensando usar un timer que ponga en "cooldown" el generador para evitar que se estén generando tantos objetos como mencionas. Es bastante sencillo usando el nodo Timer.

También está el array que guarda los obstáculos generados y no se está usando para nada ahora que lo veo.

Otro problema que hay con el generador es que al menos el primer objeto aparece demasiado cerca del jugador y eso es un problema.
